/**
 * PROPS — oggetti di scena condivisi, stile Pokémon HGSS/BW.
 * Contorni K morbidi, 3 toni per materiale, luce dall'alto.
 * footprint = tile solidi alla base dello sprite (ancorati in basso a sx).
 */
import { sprite } from './format'
import type { PropKey, PropSpec } from './catalog'

// ------------------------------------------------------------ alberi

const tree: PropSpec = {
  sprite: sprite([
    '.............KKKKKK.............',
    '...........KKvvvvvvKK...........',
    '..........KvvggggggvvK..........',
    '........KKggggggggggggKK........',
    '.......KggggggggggggggggK.......',
    '......KgggggGgggggGggggggK......',
    '.....KggggggggggggggggggggK.....',
    '....KGgggggggvggggggggggggGK....',
    '...KGGgggggggggggGggggggggGGK...',
    '..KGgggggGggggggggggggvgggggGK..',
    '..KGgggggggggggGgggggggggggGGK..',
    '.KGGgggGggggggggggggGgggggggGGK.',
    '.KGGggggggggvggggggggggggggGGGK.',
    'KGGGgggggGggggggggggGgggggggGGGK',
    'KGGGggggggggggggvggggggggggGGGGK',
    'KGGGGgggGgggggggggggggGggggGGGGK',
    'KGGGGGggggggggGggggggggggGGGGGGK',
    'KGVGGGGgggggggggggGggggGGGGGVGGK',
    '.KVGGGGGGGGGGGGGGGGGGGGGGGGVVK..',
    '.KVVGGGGVGGGGGGGGGGGGVGGGGVVVK..',
    '..KVVGGGGGGGGGVGGGGGGGGGGVVVK...',
    '...KVVVGGGVGGGGGGGGVGGGVVVVK....',
    '....KVVVVVGGVGGGGVGGVVVVVVK.....',
    '.....KKVVVVVVVVVVVVVVVVVKK......',
    '.......KKVVVTTVVVTTVVVKK........',
    '.........KKKTTUuuTTTKKK.........',
    '............KTTUuTTK............',
    '.............KUuuUK.............',
    '.............KUuuUK.............',
    '.............KUutUK.............',
    '.............KUuuUK.............',
    '.............KUuuUK.............',
    '.............KUutUK.............',
    '............KUuuuUK.............',
    '............KUuutUK.............',
    '...........KUuuuuUUK............',
    '..........KUuuuuuuUUK...........',
    '.........KUUuuuuuuUUUK..........',
    '........KKUUUuuuuUUUUKK.........',
    '.........KKKKKKKKKKKKK..........',
  ]),
  solid: true,
  footprint: { w: 2, h: 1 },
}

const pine: PropSpec = {
  sprite: sprite([
    '...........KK...........',
    '..........KvvK..........',
    '..........KvgK..........',
    '.........KvgggK.........',
    '.........KggGVK.........',
    '........KgggGVVK........',
    '.......KgggGGVVVK.......',
    '......KKgGGGVVVVKK......',
    '........KgggGGVK........',
    '.......KvgggGVVVK.......',
    '......KgggGGGVVVVK......',
    '.....KgggGGVVVVVVVK.....',
    '....KKgGGGVVVVVVVVKK....',
    '.......KgggGGVVVK.......',
    '......KvgggGGVVVVK......',
    '.....KgggGGGVVVVVVK.....',
    '....KgggGGVVVVVVVVVK....',
    '...KKgGGGVVVVVVVVVVKK...',
    '......KgggGGVVVVVK......',
    '.....KgggGGGVVVVVVK.....',
    '....KgggGGVVVVVVVVVK....',
    '...KgggGGGVVVVVVVVVVK...',
    '..KgGGGVVVVVVVVVVVVVVK..',
    '.KKGGVVVVVVTTVVVVVVVVKK.',
    '...KKKVVVTTTTTTVVVKKK...',
    '......KKTTTTTTTTKK......',
    '........KKKTTKKK........',
    '..........KUuK..........',
    '..........KUuK..........',
    '..........KUuK..........',
    '..........KUuK..........',
    '..........KUuK..........',
    '..........KUtK..........',
    '..........KUuK..........',
    '..........KUuK..........',
    '.........KUuuUK.........',
    '.........KUutUK.........',
    '........KUUuuuUK........',
    '.......KKUUuuUUKK.......',
    '........KKKKKKKK........',
  ]),
  solid: true,
  footprint: { w: 1, h: 1 },
}

const cypress: PropSpec = {
  sprite: sprite([
    '.......KK.......',
    '......KvVK......',
    '......KvVK......',
    '.....KvgVVK.....',
    '.....KvgVVK.....',
    '.....KggVVK.....',
    '....KvggVVVK....',
    '....KggGVVVK....',
    '....KggGVVVK....',
    '...KvggGVVVVK...',
    '...KggGGVVVVK...',
    '...KggGGVVVVK...',
    '...KgGGVVVVVK...',
    '...KggGGVVVVK...',
    '...KgGGVVVVVK...',
    '...KgGGVVVVVK...',
    '...KgGGVVVVVK...',
    '...KgGGVVVTVK...',
    '...KgGGVVVVVK...',
    '...KGGVVVVTVK...',
    '...KGGVVVVVVK...',
    '...KGGVVVTVVK...',
    '....KGVVVVVK....',
    '....KGVVVTVK....',
    '....KGVVVVVK....',
    '....KGVVVVVK....',
    '.....KGVVVK.....',
    '.....KGVTVK.....',
    '.....KGVVVK.....',
    '......KVVK......',
    '......KVVK......',
    '.......KK.......',
    '......KUuK......',
    '......KUuK......',
    '......KUuK......',
    '......KUuK......',
    '.....KUuuUK.....',
    '.....KUutUK.....',
    '....KUUuuUUK....',
    '.....KKKKKK.....',
  ]),
  solid: true,
  footprint: { w: 1, h: 1 },
}

const palm: PropSpec = {
  sprite: sprite([
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '.....KKK....KKK.........',
    '...KKgggKKKKgggKK.......',
    '..KgggggGKKGgggggK......',
    '.KgggKKgggGgggKKgggK....',
    'KgggK.KGgggggGK.KgggK...',
    'KggK...KGgggGK...KggGK..',
    'KgK...KGgggggGK...KgGK..',
    '.K...KGgKUuKgGGK...KK...',
    '.....KGK.KuUKGGK........',
    '....KGK..KuuK.KGK.......',
    '.....K...KuuK..K........',
    '.........KuuUK..........',
    '.........KuuUK..........',
    '..........KuuK..........',
    '..........KuuUK.........',
    '..........KuuUK.........',
    '..........KtuUK.........',
    '...........KuuK.........',
    '...........KuuUK........',
    '...........KuuUK........',
    '...........KtuUK........',
    '...........KuuUK........',
    '...........KuuUK........',
    '...........KuuUK........',
    '...........KtuUK........',
    '..........KuuuUK........',
    '..........KuuuUK........',
    '..........KuutUK........',
    '..........KuuuUK........',
    '.........KUuuuUK........',
    '.........KUuuuUUK.......',
    '........KUuuuuuUUK......',
    '........KUUuuuUUUK......',
    '.........KKUUUKKK.......',
    '..........KKKKK.........',
  ]),
  solid: true,
  footprint: { w: 1, h: 1 },
}

const olive: PropSpec = {
  sprite: sprite([
    '........................',
    '........................',
    '........................',
    '........KKKKK...........',
    '.....KKKgggggKKK........',
    '....KgggvgggaggvK.......',
    '..KKgggagggggagggKK.....',
    '.KgggagggvggggggaggK....',
    '.KgagggggggagggvgggK....',
    'KggggggvggagggggggagK...',
    'KgagggagggggvgggggggK...',
    'KgGgagggggagggagagGgK...',
    '.KGgggagGgggGgagaGGK....',
    '.KGGgagagagGagGaGGGK....',
    '..KGGgaGgagagGaGGGK.....',
    '...KKGGGgaGGGGGGKK......',
    '.....KKGGKUuKGKK........',
    '.........KUuK...........',
    '........KUuuK...........',
    '........KUuK............',
    '.......KUuuK............',
    '.......KUuK.............',
    '.......KUuuK............',
    '.......KUuuUK...........',
    '......KUuuuUK...........',
    '......KUuutUK...........',
    '......KUuuuUK...........',
    '.....KUUuuuUUK..........',
    '....KUUuuuuuUUK.........',
    '....KUUUuuUUUUK.........',
    '.....KKKUUKKKK..........',
    '.......KKKK.............',
  ]),
  solid: true,
  footprint: { w: 1, h: 1 },
}

// --------------------------------------------------- cespugli e fiori

const bush: PropSpec = {
  sprite: sprite([
    '....KKKGGKK.....',
    '..KKgggggggKK...',
    '.KgggvggvggggK..',
    '.KgvggggggggvK..',
    'KgggggvggggggGK.',
    'KGgggggggggvgGK.',
    'KGGgggGggggggGK.',
    '.KGGgggggGgGGK..',
    '..KKGGGGGGGKK...',
    '....KKKKKKK.....',
  ]),
  solid: true,
  footprint: { w: 1, h: 1 },
}

const roseBush: PropSpec = {
  sprite: sprite([
    '....KKKGGKK.....',
    '..KKgggPgggKK...',
    '.KggPgggggPggK..',
    '.KgQPgvgggggvK..',
    'KggggggggPQggGK.',
    'KGgPggggggggPGK.',
    'KGQPgGggPggggGK.',
    '.KGGggggQgGGGK..',
    '..KKGGGGGGGKK...',
    '....KKKKKKK.....',
  ]),
  solid: true,
  footprint: { w: 1, h: 1 },
}

const flowerPatch: PropSpec = {
  sprite: sprite([
    '................',
    '................',
    '................',
    '................',
    '..p....w....p...',
    '.pYp..wYw..pYp..',
    '..p.G..w.G..p...',
    '..G.....G...G...',
  ]),
  solid: false,
  footprint: { w: 1, h: 1 },
}

// ----------------------------------------------------------- arredo

const bench: PropSpec = {
  sprite: sprite([
    '................................',
    '................................',
    '................................',
    '.KKKKKKKKKKKKKKKKKKKKKKKKKKKKK..',
    '.KtttttttttttttttttttttttttttK..',
    '.KuuuuuuuuuuuuuuuuuuuuuuuuuuuK..',
    '.KtttttttttttttttttttttttttttK..',
    '.KuuuuuuuuuuuuuuuuuuuuuuuuuuuK..',
    '.KKKKKKKKKKKKKKKKKKKKKKKKKKKKK..',
    '.KttttttttttttttttttttttttttttK.',
    '.KuuuuuuuuuuuuuuuuuuuuuuuuuuuuK.',
    '.KUUUUUUUUUUUUUUUUUUUUUUUUUUUUK.',
    '..KUUK...................KUUK...',
    '..KUUK...................KUUK...',
    '..KUUK...................KUUK...',
    '..KKKK...................KKKK...',
  ]),
  solid: true,
  footprint: { w: 2, h: 1 },
}

const lamp: PropSpec = {
  sprite: sprite([
    '......KKKK......',
    '.....KKyyKK.....',
    '....KyyyyyyK....',
    '....KywwyyyK....',
    '....KyyyyyYK....',
    '....KyyyyYYK....',
    '.....KYYYYK.....',
    '....KKKKKKKK....',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '......KXxK......',
    '.....KXXxxK.....',
    '.....KXXxxK.....',
    '....KXXXxxxK....',
    '...KXXXXxxxxK...',
    '...KXXXXXXXXK...',
    '....KKKKKKKK....',
  ]),
  solid: true,
  footprint: { w: 1, h: 1 },
}

const fountain: PropSpec = {
  sprite: sprite([
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '..............ii................',
    '.............ibbi...............',
    '.............ibbi...............',
    '..............ii................',
    '............KKccKK..............',
    '...........KcbbbbcK.............',
    '...........KcbibbcK.............',
    '............KccccK..............',
    '.......i....KCnnCK....i.........',
    '......ibi..KCccccCK..ibi........',
    '.......i...KCccccCK...i.........',
    '...........KCnnnnCK.............',
    '......KKKKKKCnnnnCKKKKKK........',
    '....KKccccccccccccccccccKK......',
    '...KccbbbbbbbbbbbbbbbbbbccK.....',
    '..KcbbibbbbbibbbbbbbibbbbbcK....',
    '..KcbbbbbbbbbbbibbbbbbbbbbcK....',
    '.KcbbibbbbibbbbbbbbbibbbbbbcK...',
    '.KcbbbbbbbbbbbbibbbbbbbbibbcK...',
    '.KCcbbbbbbbbbbbbbbbbbbbbbbcCK...',
    '.KCCccbbbbbbbbbbbbbbbbbbccCCK...',
    '.KnCCCccccccccccccccccccCCCnK...',
    '.KnnCCCCCCCCCCCCCCCCCCCCCCnnK...',
    '..KnnnCCCCCCCCCCCCCCCCCCnnnK....',
    '...KKnnnnnnnnnnnnnnnnnnnnKK.....',
    '.....KKKKKKKKKKKKKKKKKKKK.......',
  ]),
  solid: true,
  footprint: { w: 2, h: 2 },
}

const statue: PropSpec = {
  sprite: sprite([
    '................',
    '................',
    '................',
    '...KKK..KKK.....',
    '..KcccKKcccK....',
    '..KcCcKKcCcK....',
    '...KcKKKKcK.....',
    '..KccccccccK....',
    '.KccccccccccK...',
    '.KcCCcccccCcK...',
    '.KcCnCCCCnCcK...',
    '.KcCCnCCnCCcK...',
    '.KcCCCnnCCCcK...',
    '..KcCCCCCCcK....',
    '..KcCCCCCCcK....',
    '..KcCCnCCCcK....',
    '..KCCCnCCCCK....',
    '..KCCnnnCCCK....',
    '.KcCCCCCCCCcK...',
    '.KCCCCCCCCCCK...',
    '.KCCCCCCCCCCK...',
    '.KccccccccccccK.',
    '.KcCCCCCCCCCCcK.',
    '.KcCCCCCCCCCCcK.',
    'KccccccccccccccK',
    'KcCCCCCCCCCCCCnK',
    'KcCCCCCCCCCCCCnK',
    'KcCCCCCCCCCCCCnK',
    'KcCCCCCCCCCCCCnK',
    'KCCnnnnnnnnnnnnK',
    'KCnnnnnnnnnnnnNK',
    'KKKKKKKKKKKKKKKK',
  ]),
  solid: true,
  footprint: { w: 1, h: 1 },
}

const umbrella: PropSpec = {
  sprite: sprite([
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '...........KK...........',
    '.......KKKKwwKKKK.......',
    '.....KKppwwwwwwppKK.....',
    '....KpppPwwwwwwPpppK....',
    '..KKpppppPwwwwPpppppKK..',
    '.KppppppppPwwPppppppppK.',
    '.KPppppppppPPpppppppppK.',
    '.KQPPPPPPPPPPPPPPPPPPQK.',
    '..KKQQQQQQQKKQQQQQQQKK..',
    '....KKKKKKKuuKKKKKKK....',
    '...........KuK..........',
    '...........KuK..........',
    '...........KuK..........',
    '...........KuK..........',
    '...........KuK..........',
    '...........KuK..........',
    '...........KuK..........',
    '...........KuK..........',
    '...........KuK..........',
    '...........KuK..........',
    '...........KuK..........',
    '..........KKuKK.........',
    '..........KuuuK.........',
    '...........KKK..........',
  ]),
  solid: true,
  footprint: { w: 1, h: 1 },
}

const sunbed: PropSpec = {
  sprite: sprite([
    '................',
    '................',
    '..KKKKKKKKKKKK..',
    '..KtuuuuuuuutK..',
    '..KuWWWWWWWWuK..',
    '..KuWWWWWWWWuK..',
    '..KuAAAAAAAAuK..',
    '..KuWWWWWWWWuK..',
    '..KubbbbbbbbuK..',
    '..KuWWWWWWWWuK..',
    '..KuWWWWWWWWuK..',
    '..KubbbbbbbbuK..',
    '..KuWWWWWWWWuK..',
    '..KuWWWWWWWWuK..',
    '..KubbbbbbbbuK..',
    '..KuWWWWWWWWuK..',
    '..KuWWWWWWWWuK..',
    '..KubbbbbbbbuK..',
    '..KuWWWWWWWWuK..',
    '..KuAWWWWWWAuK..',
    '..KuuuuuuuuuuK..',
    '..KtuuuuuuuutK..',
    '..KKKKKKKKKKKK..',
    '................',
  ]),
  solid: true,
  footprint: { w: 1, h: 1 },
}

const towel: PropSpec = {
  sprite: sprite([
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..qqqqqqqqqqqq..',
    '.qppppppppppppq.',
    '.qpwwwwwwwwwwpq.',
    '.qppppppppppppq.',
    '.qpPPPPPPPPPPpq.',
    '.qppppppppppppq.',
    '.qpwwwwwwwwwwpq.',
    '.qppppppppppppq.',
    '.qpPPPPPPPPPPpq.',
    '.qppppppppppppq.',
    '.qpwwwwwwwwwwpq.',
    '.qppppppppppppq.',
    '.qpPPPPPPPPPPpq.',
    '.qppppppppppppq.',
    '.qpwwwwwwwwwwpq.',
    '.qppppppppppppq.',
    '.qppppppppppppq.',
    '..qqqqqqqqqqqq..',
  ]),
  solid: false,
  footprint: { w: 1, h: 1 },
}

const table: PropSpec = {
  sprite: sprite([
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '..........KKKKKKKKKKKK..........',
    '........KKWWWWWWWWWWWWKK........',
    '.......KWWWWWWWWWWWWWWWWK.......',
    '.......KWWWWWWWWWWWWWWWWK.......',
    '.......KWAWWWWWWWWWWWAWWK.......',
    '.......KAWWWWWWWWWWWWWWAK.......',
    '........KKAAAAAAAAAAAAKK........',
    '..KKKK....KKKKKKKKKK....KKKK....',
    '.KttttK.....KuK..KuK...KttttK...',
    '.KuuuuK.....KuK..KuK...KuuuuK...',
    '.KuKKuK.....KuK..KuK...KuKKuK...',
    '.KuK.KuK...KuuK..KuuK.KuK.KuK...',
    '.KuK.KuK...KKK....KKK.KuK.KuK...',
    '.KKK.KKK..............KKK.KKK...',
  ]),
  solid: true,
  footprint: { w: 2, h: 1 },
}

const sign: PropSpec = {
  sprite: sprite([
    '................',
    '................',
    '.KKKKKKKKKKKKK..',
    'KtttttttttttttK.',
    'KtuUuUUuUUuUutK.',
    'KttttttttttttuK.',
    'KtuUUuUuUUuUutK.',
    'KttttttttttttuK.',
    'KuuuuuuuuuuuuuK.',
    '.KKKKKuuKKKKKK..',
    '.....KuuK.......',
    '.....KuuK.......',
    '.....KuuK.......',
    '....KKuuKK......',
    '....KUuuUK......',
    '.....KKKK.......',
  ]),
  solid: true,
  footprint: { w: 1, h: 1 },
}

const pot: PropSpec = {
  sprite: sprite([
    '................',
    '................',
    '................',
    '................',
    '....P..g..P.....',
    '...PYP.gg.PYP...',
    '..G.P.gGg..P.G..',
    '...GgKKgKKgG....',
    '...KKoooooKK....',
    '...KooooootK....',
    '....KoooooK.....',
    '....KooootK.....',
    '....KOoooOK.....',
    '....KOOOOOK.....',
    '.....KKKKK......',
    '................',
  ]),
  solid: true,
  footprint: { w: 1, h: 1 },
}

const barrel: PropSpec = {
  sprite: sprite([
    '................',
    '................',
    '................',
    '................',
    '....KKKKKKK.....',
    '...KUuuuuuUK....',
    '..KtuutttuutK...',
    '..KUUUUUUUUUK...',
    '..KtuuutuuutK...',
    '..KtuuttuuttK...',
    '..KuuutuuuutK...',
    '..KUUUUUUUUUK...',
    '..KuuututuuuK...',
    '..KUuuuuuuuUK...',
    '...KKKKKKKKK....',
    '................',
  ]),
  solid: true,
  footprint: { w: 1, h: 1 },
}

const vine: PropSpec = {
  sprite: sprite([
    '................................',
    '................................',
    '................................',
    '..KK........................KK..',
    '.KggKKKKKKKKKKKKKKKKKKKKKKKKggK.',
    'KgvggggggggggggggggggggggggggvgK',
    'KgggGgvgggGggggvggGgggvgggGggggK',
    'KGgggggGggggGggggggggGgggggGggGK',
    '.KGgGggggmGgggGgmgggggGgmgggGGK.',
    '.KGmmGgggmmGggGmmGggGgmmGggGGGK.',
    '..KmmmGgmmmGgGmmmGgGgmmmGgGGK...',
    '..KmMmKKmMmKKKmMmKKKKmMmKKKK....',
    '...KMK.KmMK...KMK....KMK........',
    '....K...KK.....K......K.........',
    '...KUuK..............KUuK.......',
    '...KUuK..............KUuK.......',
    '...KUuK..............KUuK.......',
    '...KUuK..............KUuK.......',
    '...KUuK..............KUuK.......',
    '...KUuK..............KUuK.......',
    '...KUuK..............KUuK.......',
    '..KKUuKK............KKUuKK......',
    '..KUUuUK............KUUuUK......',
    '...KKKK..............KKKK.......',
  ]),
  solid: true,
  footprint: { w: 2, h: 1 },
}

const buoy: PropSpec = {
  sprite: sprite([
    '................',
    '................',
    '................',
    '................',
    '......KKK.......',
    '.....KKrK.......',
    '.....KrrrK......',
    '....KrrwrrK.....',
    '....KrwrrrK.....',
    '....KwwwwwK.....',
    '....KrrrrrK.....',
    '...KRrrrrrRK....',
    '...KRRrrrRRK....',
    '..iKKRRRRRKKi...',
    '.ibbKKKKKKKbbi..',
    '..ii.......ii...',
  ]),
  solid: false,
  footprint: { w: 1, h: 1 },
}

const rocks: PropSpec = {
  sprite: sprite([
    '.......KKK......................',
    '.....KKcccK.........KKKK........',
    '....KcccCCcK......KKccccK.......',
    '...KccCCCCCcK....KcccCCCcK......',
    '..KccCCCCCCCK...KccCCCCCCK......',
    '..KcCCCnCCCCcK.KccCCCCnCCcK.....',
    '.KcCCCCnnCCCCK.KcCCCnnCCCCK.....',
    '.KcCCnnCCCCCnKKcCCCCnCCCCnK.....',
    '.KCCCnCCCCCnnKKCCCnnCCCCnnK.....',
    'KcCCCCCCCnnnCCCCCCCCCCCnnnCK....',
    'KCCnnCCCCCnnnCCCnnCCCCCnnnnK....',
    'KCnnnnCCCCCCCCCnnnnCCCCCCnnK....',
    'KnnNNnnnCCCCnnnnNNnnnCCCnnnK....',
    'KNnnnnnnnnnnnnnnnnnnnnnnnnNK....',
    '.KKNNNnnnnNNNKKKNNnnnnNNNKK.....',
    '...KKKKKKKKK....KKKKKKKKK.......',
  ]),
  solid: true,
  footprint: { w: 2, h: 1 },
}

const gull: PropSpec = {
  sprite: sprite([
    '................',
    '................',
    '.....KK.........',
    '....KwwK........',
    '....KwwKY.......',
    '....KwwwK.......',
    '..KKwwwwK.......',
    '.KwwwwwwwK......',
    '.KAwwwwwwK......',
    '..KAAwwwwK......',
    '...KKAAwwK......',
    '.....KKAKK......',
    '......KwK.......',
    '......KKK.......',
    '.....KYYK.......',
    '.....K..K.......',
  ]),
  solid: false,
  footprint: { w: 1, h: 1 },
}

const cat: PropSpec = {
  sprite: sprite([
    '................',
    '................',
    '...KK...KK......',
    '..KttK.KttK.....',
    '..KtttKKtttK....',
    '.KttttttttttKK..',
    '.KtKttKttttttK..',
    '.KtWtttttuuttK..',
    '.KtttttttttttKK.',
    '.KuutttuutttttK.',
    '.KtttttttttuutK.',
    '.KKtttttttttttK.',
    '..KuuuuuuuuuutK.',
    '...KKKKKKKKKuK..',
    '............KK..',
    '................',
  ]),
  solid: false,
  footprint: { w: 1, h: 1 },
}

// ---------------------------------------------------------------------

export const PROPS: Record<PropKey, PropSpec> = {
  tree,
  pine,
  cypress,
  palm,
  olive,
  bush,
  roseBush,
  flowerPatch,
  bench,
  lamp,
  fountain,
  statue,
  umbrella,
  sunbed,
  towel,
  table,
  sign,
  pot,
  barrel,
  vine,
  buoy,
  rocks,
  gull,
  cat,
}
